substitutions:
  ui_language: es
  screen_width: "480"
  screen_height: "320"

esphome:
  name: nabla-simulator

packages:
  locale: !include ../locales/${ui_language}.yaml
  hardware: !include hardware/sdl.yaml
  theme: !include ../theme/nabla.yaml
  ui: !include ../examples/hello-world/ui.yaml
