substitutions:
  nabla_resource_root: ".."
  nabla_device_model: "ESPHome simulator"

esphome:
  includes:
    - ${nabla_resource_root}/components/device-info/runtime.h
  on_boot:
    priority: -90
    then:
      - script.execute: device_info_refresh

script:
  - id: device_info_refresh
    then:
      - lambda: nabla_info::refresh("${nabla_device_model}", "${tr_info_disconnected}", "${tr_info_unavailable}");

interval:
  - interval: 1s
    then:
      - script.execute: device_info_refresh
