// Latin keyboard maps for LVGL; extends text entry while retaining the shared editor behavior.

#pragma once
#include "lvgl.h"
namespace nabla_keyboard {
inline const char *const lower[] = {"1#", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", LV_SYMBOL_BACKSPACE, "\n", "ABC", "a", "s", "d", "f", "g", "h", "j", "k", "l", "ñ", "\n", "z", "x", "c", "v", "b", "n", "m", "á", "é", "í", "ó", "ú", "ü", "\n", LV_SYMBOL_CLOSE, LV_SYMBOL_LEFT, " ", LV_SYMBOL_RIGHT, LV_SYMBOL_OK, ""};
inline const lv_buttonmatrix_ctrl_t lower_control[] = {static_cast<lv_buttonmatrix_ctrl_t>(2), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(2), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(3), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1)};
inline const char *const upper[] = {"1#", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", LV_SYMBOL_BACKSPACE, "\n", "abc", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Ñ", "\n", "Z", "X", "C", "V", "B", "N", "M", "Á", "É", "Í", "Ó", "Ú", "Ü", "\n", LV_SYMBOL_CLOSE, LV_SYMBOL_LEFT, " ", LV_SYMBOL_RIGHT, LV_SYMBOL_OK, ""};
inline const lv_buttonmatrix_ctrl_t upper_control[] = {static_cast<lv_buttonmatrix_ctrl_t>(2), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(2), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(3), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1)};
inline const char *const symbols[] = {"abc", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", LV_SYMBOL_BACKSPACE, "\n", "!", "\"", "#", "$", "%", "&", "'", "(", ")", "*", "+", "\n", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "\n", "[", "\\", "]", "^", "_", "`", "{", "|", "}", "~", "\n", LV_SYMBOL_CLOSE, LV_SYMBOL_LEFT, " ", LV_SYMBOL_RIGHT, LV_SYMBOL_OK, ""};
inline const lv_buttonmatrix_ctrl_t symbols_control[] = {static_cast<lv_buttonmatrix_ctrl_t>(2), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(3), static_cast<lv_buttonmatrix_ctrl_t>(1), static_cast<lv_buttonmatrix_ctrl_t>(1)};
inline void install(lv_obj_t *keyboard) {
  lv_keyboard_set_map(keyboard,LV_KEYBOARD_MODE_TEXT_LOWER,lower,lower_control);
  lv_keyboard_set_map(keyboard,LV_KEYBOARD_MODE_TEXT_UPPER,upper,upper_control);
  lv_keyboard_set_map(keyboard,LV_KEYBOARD_MODE_SPECIAL,symbols,symbols_control);
  lv_keyboard_set_mode(keyboard,LV_KEYBOARD_MODE_TEXT_LOWER);
}
}
