# Embed the offline page without external runtime assets.
from pathlib import Path
root=Path(__file__).resolve().parents[1]/"external_components/nabla_web"
html=(root/"page.html").read_text()
(root/"page.h").write_text('// Generated by tools/embed_web_page.py; edit page.html instead.'+chr(10)+'#pragma once'+chr(10)+'namespace esphome::nabla_web { inline constexpr char PAGE[]=R"NABLA('+html+')NABLA"; }'+chr(10))
